spring:
  datasource:
    #    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jpa_ex?useSSL=false&serverTimezone=Asia/Seoul
    username: jpa_user
    password: jpa_user

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    generate-ddl: false

  thymeleaf:
    cache: false

  devtools:
    livereload:
      enabled: true


logging:
  level:
    org.hibernate: info
    org.springframework.web: info
    org.dong: info